version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    networks:
      - frontend_backend_net
      - backend_db_net


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - frontend_backend_net



  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_db_net



volumes:
  pgdata:


networks:
  frontend_backend_net:
    driver: bridge
  backend_db_net:
    driver: bridge

